### ISSUE TITLE
Uninstaller does not remove program

### ISSUE THREAD

**Issue by ManZosh** [alekkowalczyk/a7JsonViewer#2]
I installed your program but found something else that suites my needs. I'd like to uninstall it but it doesn't seem to come with an uninstaller or it isn't registered.
![image](https://user-images.githubusercontent.com/28317348/72762297-166f5f00-3bad-11ea-92e1-bcc2e1095958.png)

I also can't open its shortcut's file location as it's just a ms-appref... What kind of program are you pushing here man?

**Comment by alekkowalczyk** [comment]
Not sure, looks like something went wrong during installation, how to uninstall such click-once failed case can be found, e.g. here:

https://stackoverflow.com/questions/1266858/uninstall-clickonce-clients
https://stackoverflow.com/questions/10766334/how-to-find-the-target-exe-file-of-appref-ms

As of what kind of program, it's open source so anyone can check, unfortunately I don't have time anymore for maintenance of it, but open for forks and/or pull requests if something is needed.
